{
 "title": "HTTP Input v1.0.0",
 "tags": [ "Logprep" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Behavior Over Selected Timeframe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Durchsatz / Prozess",
   "type": "stat",
   "description": "Anzahl der Events, die Logprep schafft aus kafka sich abzuholen.  Ereigniss pro Sekunde je Logprep Prozess.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logprep_number_of_processed_events_total{component=\"input\"}[1m])) / sum(count by(pod) ((logprep_config_refresh_interval)) -1 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Processing Times",
   "type": "stat",
   "description": "Processing times of input connector. ",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"input\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"input\"}[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Processing Times",
   "type": "stat",
   "description": "Duration of all connector and pipeline processing times combined.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg by (component)((increase(logprep_processing_time_per_event_sum{component=~\"input|output|pipeline\"}[$__range])/increase(logprep_processing_time_per_event_count{component=~\"input|output|pipeline\"}[$__range]) > 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input/Output Ratio",
   "type": "stat",
   "description": "Stellt die Ratio von eingehenden und ausgehenden Logs dar. Im Falle der Verwendung des Selective Extractors muss beachtet werden, dass immer doppelt so viele Logs ausgehen geschrieben werden. Gleiches gilt für Logs mit vielen Pseudonymen oder SREs.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"output\"}[$__range])) / sum(increase(logprep_number_of_processed_events_total{component=\"input\"}[$__range])>0)",
     "legendFormat": "Relative"
    }
   ]
  },
  {
   "title": "Incoming Events",
   "type": "stat",
   "description": "The increase of number of incoming events",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"input\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "description": "Gibt an, wieviel logs grad in der Queue sind",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(logprep_message_backlog_size{component=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "The increase of number of warnings in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logprep_number_of_warnings_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Version",
   "type": "stat",
   "description": "Shows the currently active config version of logprep, if specified.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logprep_version_info) by (logprep, config)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Durchsatz Gesamt",
   "type": "stat",
   "description": "Anzahl der Events, die Logprep schafft aus kafka sich abzuholen.  Ereigniss pro Sekunde.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logprep_number_of_processed_events_total{component=\"input\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Processing Times",
   "type": "stat",
   "description": "Average processing times of all output connectors",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"output\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"output\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Processing Times",
   "type": "stat",
   "description": "Is the sum of the whole pipeline: parsing event, passing it through the pipeline and sending it to the output connector.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"pipeline\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"pipeline\"}[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "Anzahl der laufenden Pipeline Prozesse",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(pod) ((logprep_config_refresh_interval)) -1 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Events",
   "type": "stat",
   "description": "The increase of number of outgoing events",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"output\"}[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "stat",
   "description": "Anzahl der Requests auf dem Konnektor",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_http_requests_total{component=\"input\"}[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The increase of number of errors in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logprep_number_of_errors_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logprep Version",
   "type": "stat",
   "description": "Shows the currently active logprep version.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logprep_version_info) by (logprep, config)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Processed Event Rate per Connector per Second",
   "type": "timeseries",
   "description": "Shows the per-second average of processed events per connector.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(type)(rate(logprep_number_of_processed_events_total{component=\"input\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by(type)(rate(logprep_number_of_processed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Success/Failed Event Rate per Output per Second",
   "type": "timeseries",
   "description": "Shows the difference between processed and failed events as a per-second average. Failed events are events that couldn't be parsed or where processors/rules canceled the processing due to an error. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(logprep_number_of_processed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "Processed Events"
    },
    {
     "expr": "sum(rate(logprep_number_of_failed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "Failed Events"
    }
   ]
  },
  {
   "title": "Processing Time Per Connector",
   "type": "timeseries",
   "description": "Shows the processing time per connector ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (type)(increase(logprep_processing_time_per_event_sum{component=\"input\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"input\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type)(increase(logprep_processing_time_per_event_sum{component=\"output\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"output\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Kafka: Messages in per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"public.bw.monitoring.event.sap-sal\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "description": "Das Kafka Consumer Lag (Verbraucherverzögerung) gibt die Verzögerung zwischen Kafka-Produzenten und -Konsumenten an. Wenn die Geschwindigkeit der Datenproduktion die Geschwindigkeit, mit der sie verbraucht werden, bei weitem übersteigt, kommt es bei Consumer Groups (Verbrauchergruppen) zu Verzögerungen.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"sap-sal\",topic=~\"public.bw.monitoring.event.sap-sal\", namespace=~\"core\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  { "title": "Errors / Warnings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Number of Errors",
   "type": "timeseries",
   "description": "in the selected time range",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component) (increase(logprep_number_of_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Warnings",
   "type": "timeseries",
   "description": "in the selected time range",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component) (increase(logprep_number_of_warnings_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}