# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  apt_packages:
    - "pandoc"
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "16"
    rust: "latest"
    # golang: "1.17"
  # jobs:
  #   pre_install:
  #     - "curl https://sh.rustup.rs -sSf | bash -s -- -y"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: ./doc/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - doc
