---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configurations
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configurations }}
  {{ $value.name }}: |-
  {{- toYaml $value.data | nindent 4 }}
  {{- end }}
