---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logprep.fullname" . }}-configurations
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configurations }}
  {{- if $value.data }}
  {{ $value.name }}: |-
  {{- toYaml $value.data | nindent 4 }}
  {{- end }}
  {{- end }}
