---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-exporter
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  exporter-config.yaml: |
    metrics:
      enabled: {{ .Values.exporter.enabled }}
      port: {{ default 8000 .Values.exporter.port }}
