---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-exporter
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/application: logprep
data:
  exporter-config.yaml: |
    metrics:
      enabled: {{ .Values.exporter.enabled }}
      port: {{ default 8000 .Values.exporter.port }}
