{{- if .Values.input -}}
{{- if eq .Values.input.type "http_input" -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-http-input
spec:
  ports:
    - name: http-input
      port: {{ .Values.input.uvicorn_config.port }}
      targetPort: {{ .Values.input.uvicorn_config.port }}
      appProtocol: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
{{- end}}
{{- end}}
