---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-input
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  input-config.yaml: |
    input:
      {{- if .Values.input }}
      {{- trimSuffix "_input" .Values.input.type | nindent 6}}:
      {{- toYaml .Values.input | nindent 8}}
      {{- else }}
      stdin:
        type: file_input
        logfile_path: /dev/stdin
        start: end
        watch_file: true
        interval: 1
      {{- end }}
