---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logprep.fullname" . }}-logger
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  logger-config.yaml: |
    logger:
      {{- toYaml .Values.logger | nindent 6}}
