---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-logger
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/application: logprep
data:
  logger-config.yaml: |
    logger:
      {{- toYaml .Values.logger | nindent 6}}
