---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-logger
  labels:
    {{- include "logprep.labels" . | nindent 4 }}
data:
  logger-config.yaml: |
    logger:
      {{- toYaml .Values.logger | nindent 6}}
