---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-metrics-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-logprep
    app.kubernetes.io/application: logprep
data:
  metrics-config.yaml: |
    metrics:
      enabled: {{ .Values.exporter.enabled }}
      port: {{ default 8000 .Values.exporter.port }}
