{
 "title": "Logprep Processors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "label_values(logprep_number_of_processed_events_total{component=\"rule\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Processors Types",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(logprep_number_of_processed_events_total{component=\"rule\"}) by (type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Processors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(logprep_number_of_processed_events_total{component=\"rule\"}) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(logprep_number_of_processed_events_total{component=\"rule\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Applied Rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"rule\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Details of $processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "processor" },
  {
   "title": "Number of Rules",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(logprep_number_of_processed_events_total{component=\"rule\", name=\"$processor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(logprep_number_of_warnings_total{component=\"rule\", name=\"$processor\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Applied Rules",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"rule\", name=\"$processor\"}[1m]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Average Processing Time per Applied Rule",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"rule\", name=\"$processor\"}[1m]) / increase(logprep_processing_time_per_event_count{component=\"rule\", name=\"$processor\"}[1m])>0)",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Average Processing Time per Applied Rule",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"rule\", name=\"$processor\"}[1m]) / increase(logprep_processing_time_per_event_count{component=\"rule\", name=\"$processor\"}[1m])>0)",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Number of Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(logprep_number_of_errors_total{component=\"rule\", name=\"$processor\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processor Specific - Amides", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Amides - Rate of New Results per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(increase(logprep_amides_total_cmdlines_total[1m]))",
     "legendFormat": "Total Results Rate"
    },
    {
     "expr": "sum(increase(logprep_amides_cached_results[1m]))",
     "legendFormat": "Cached Results Rate"
    },
    {
     "expr": "sum(increase(logprep_amides_new_results[1m]))",
     "legendFormat": "New Results Rate"
    }
   ]
  },
  {
   "title": "Amides - Rate of Cached Results per Second",
   "type": "gauge",
   "gridPos": { "h": 21, "w": 5, "x": 19, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logprep_amides_num_cache_entries)",
     "legendFormat": "New Results Rate"
    },
    {
     "expr": "sum(logprep_amides_num_cache_entries) / sum(logprep_amides_cache_load)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amides - Mean Detection Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(logprep_amides_mean_misuse_detection_time_sum[1m]) / rate(logprep_amides_mean_misuse_detection_time_count[1m])",
     "legendFormat": "Detection Time"
    }
   ]
  },
  {
   "title": "Amides - Mean Rule Attribution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(logprep_amides_mean_rule_attribution_time_sum[1m]) / rate(logprep_amides_mean_rule_attribution_time_count[1m])",
     "legendFormat": "Detection Time"
    }
   ]
  },
  {
   "title": "Processor Specific - Pseudonymizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }
  },
  {
   "title": "Rate of Pseudonymized URLs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "rate(logprep_pseudonymizer_pseudonymized_urls_total[1m])",
     "legendFormat": "Pseudonymized URLs"
    }
   ]
  },
  {
   "title": "Processor Specific - Domain Resolver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  {
   "title": "Domain Resolver - Rate of New Results per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum(increase(logprep_domain_resolver_total_urls_total[1m]))",
     "legendFormat": "Total Resolved URLs"
    },
    {
     "expr": "sum(increase(logprep_domain_resolver_resolved_cached_total[1m]))",
     "legendFormat": "Cached Resolved URLs"
    },
    {
     "expr": "sum(increase(logprep_domain_resolver_resolved_new_total[1m]))",
     "legendFormat": "New Resolved URLs"
    }
   ]
  },
  {
   "title": "Domain Resolver - Rate of Occurred Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(increase(logprep_domain_resolver_timeouts_total[1m]))",
     "legendFormat": "Total Resolved URLs"
    }
   ]
  }
 ]
}