{
 "title": "Logprep Version 0.0.1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component) (logprep_number_of_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings Output",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component) (logprep_number_of_warnings_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rules per Processor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (type)(logprep_number_of_processed_events_total{component=\"rule\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Times Connectors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(logprep_processing_time_per_event_sum{component=\"input\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"input\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(logprep_processing_time_per_event_sum{component=\"output\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"output\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Processing Times for matching Rules",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(logprep_processing_time_per_event_sum{component=\"rule\"}[1m]))/sum(increase(logprep_processing_time_per_event_count{component=\"rule\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum by (type)(increase(logprep_processing_time_per_event_sum{component=\"rule\"}[1m]))/sum by(type)(increase(logprep_processing_time_per_event_count{component=\"rule\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}