replicas: 1
serviceAccount: basic-secret

image:
  registry: ghcr.io
  repository: fkie-cad/logprep
  tag: py3.11-stable

resources:
  limits:
    memory: "2Gi"
    cpu: "1"
  requests:
    memory: "2Gi"
    cpu: "250m"

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

# Optional secrets that will be mounted into the pod
# Listed secrets are handled specially by the logprep deployment.
# Additional secrets will be mounted as usual.
# secrets:
#   certificates:
#     name: ca-cert # Name of the secret containing the ca certificate (or chain) in one data block
#   credentials:
#     name: logprep-credentials # Name of the secret containing the logprep credentials file
#   imagePullSecret:
#     name: logprep-image-pull-secret # Name of the secret containing the image pull secret
secrets: {}

# Boolean to signal to use affinity to avoid deploying multiple instances of the
# pod on the same node
affinity: false

# inject extra labels to the pod metadata
pod_extra_labels: {}

credentials: {}

# If enabled, the exporter will be started on the specified port and
# the metrics service and a prometheus PodMonitor will be deployed.
# You have to ensure, that the prometheus operator is installed and
# the PodMonitor resource is available.
exporter:
  enabled: true
  port: 8000
  service_port: 8001
  scrape_interval: 30s

# Logprep logging configuration. For more information see: https://logprep.readthedocs.io/en/latest/user_manual/configuration/index.html#configuration-file-structure
logger:
  level: INFO

input: {}

output:
  type: console_output

configurations:
  - name: logprep-config
    data:
      pipeline: []
