replicas: 1
serviceAccount: basic-secret

monitoring:
  enable: true
  podMonitor:
    endpoints:
      - targetPort: 8000
        interval: 30s

image:
  registry: ghcr.io
  repository: fkie-cad/logprep
  tag: py3.11-stable

resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "2Gi"
    cpu: "250m"

# inject extra labels to the pod metadata
pod_extra_labels:
  sidecar.istio.io/inject: "true"

credentials: {}

imagePullSecrets:
  - name: harbor-registry-secret

exporter:
  enabled: true
  port: 8000
  service_port: 8001

logger:
  level: INFO
  format: "%(asctime)-15s %(hostname)-5s %(name)-10s %(levelname)-8s: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  loggers:
    "py.warnings": { "level": "ERROR" }
    "Runner": { "level": "DEBUG" }

configurations:
  - name: logprep-config
    data:
      version: 1
      process_count: 2
      timeout: 0.1
      logger:
        level: INFO
        format: "%(asctime)-15s %(hostname)-5s %(name)-10s %(levelname)-8s: %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
        loggers:
          "py.warnings": { "level": "ERROR" }
          "Runner": { "level": "DEBUG" }

      pipeline:
        - labelername:
            type: labeler
            schema: quickstart/exampledata/rules/labeler/schema.json
            include_parent_labels: true
            specific_rules:
              - quickstart/exampledata/rules/labeler/specific
            generic_rules:
              - quickstart/exampledata/rules/labeler/generic

      input:
        kafka:
          type: confluentkafka_input
          topic: consumer
          kafka_config:
            bootstrap.servers: 127.0.0.1:9092
            group.id: cgroup3
            enable.auto.commit: "true"
            auto.commit.interval.ms: "10000"
            enable.auto.offset.store: "false"
            queued.min.messages: "100000"
            queued.max.messages.kbytes: "65536"
            statistics.interval.ms: "60000"
          preprocessing:
            version_info_target_field: Logprep_version_info
            log_arrival_time_target_field: event.ingested
            hmac:
              target: <RAW_MSG>
              key: "thisisasecureandrandomkey"
              output_field: Full_event
      output:
        opensearch:
          type: opensearch_output
          hosts:
            - 127.0.0.1:9200
          default_index: processed
          error_index: errors
          message_backlog_size: 10000
          timeout: 10000
          flush_timeout: 60
          max_retries: 3
          parallel_bulk: false
          user: admin
          secret: admin
        kafka:
          type: confluentkafka_output
          default: false
          topic: producer
          error_topic: errors
          flush_timeout: 300
          kafka_config:
            bootstrap.servers: 127.0.0.1:9092
            statistics.interval.ms: "60000"
