name: Reusable Container Build
on:
  workflow_call:
    inputs:
      tags:
        description: "Tags to apply to the image"
        required: true
        type: string
jobs:
  containerbuild:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          fetch-depth: 0
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@c818628b924a4bd863903a56c0e526db47bba6f4 # https://github.com/MrSquaare/ssh-setup-action/releases/tag/v3.1.3
        with:
          host: ${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
          private-key: ${{ secrets.BUILD_SERVER_ARM64_PRIVATE_KEY }}
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@c818628b924a4bd863903a56c0e526db47bba6f4 # https://github.com/MrSquaare/ssh-setup-action/releases/tag/v3.1.3
        with:
          host: ${{ secrets.BUILD_SERVER_ARM64_HOST_02 }}
          private-key: ${{ secrets.BUILD_SERVER_ARM64_PRIVATE_KEY }}
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@c818628b924a4bd863903a56c0e526db47bba6f4 # https://github.com/MrSquaare/ssh-setup-action/releases/tag/v3.1.3
        with:
          host: ${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
          private-key: ${{ secrets.BUILD_SERVER_NIX_ARM64_PRIVATE_KEY }}
      - name: Set up Docker
        uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # https://github.com/docker/setup-docker-action/releases/tag/v4.7.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # https://github.com/docker/login-action/releases/tag/v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
      - name: Set up Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # https://github.com/cachix/install-nix-action/releases/tag/v31.10.4
      - name: Setup SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          sudo mkdir -p /root/.ssh
          sudo cp ~/.ssh/known_hosts /root/.ssh/
      - name: Generate Image Tags
        id: image-tag
        run: |
          python - <<EOF
          import os
          image = "ghcr.io/fkie-cad/logprep"
          version = "${{ matrix.python-version }}"
          tags = "${{ inputs.tags }}".split(",")
          full_image = [f"{image}:py{version}-{tag.strip()}" for tag in tags]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as file:
              file.write(f"tags={', '.join(full_image)}")
          EOF
      - name: Build and Push Image
        id: build-and-push
        env:
          RUNNER_ENDPOINT: ssh://nixremote@${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
          RUNNER_ADDR: ${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
        run: |
          export PYTHON_VERSION="${{ matrix.python-version }}"

          # version for dev builds looks like this
          # 19.0.0.dev0+feat-abc.h31hd73
          # ^----^      ^-------^      ^
          # |           |       |------|
          # |           |       |
          # |           |       commit hash
          # |           |
          # |           branch name
          # |
          # Previous latest released version
          uv version "$(uv version --short).dev0+${GITHUB_HEAD_REF}.$(git rev-parse --short HEAD)"

          # Local AMD64 version
          # nix build .#packages.x86_64-linux.docker.python${PYTHON_VERSION//.} -o image
          # docker load < image

          ssh -vvv -o StrictHostKeyChecking=accept-new nixremote@$RUNNER_ADDR true
          nix store ping --store "ssh-ng://nixremote@$RUNNER_ADDR"

          # Remote ARM64 version
          export NIX_SSHOPTS='-o StrictHostKeyChecking=accept-new'
          nix --extra-experimental-features 'nix-command flakes' build .#packages.aarch64-linux.docker.python${PYTHON_VERSION//.}  \
            --system aarch64-linux \
            --builders "$RUNNER_ENDPOINT aarch64-linux" \
            --max-jobs 0 \
            -L \
            -v \
            -o image
          docker load < image

          for tag in $(echo "${{ steps.image-tag.outputs.tags }}" | tr ", " "\n")
          do
            docker image tag logprep:py${PYTHON_VERSION} $tag
            docker image push $tag

            digest=$(docker inspect $tag | jq --raw-output ".[].Id")

            # What happens with multiple tags?
            echo "digest=$digest" >> $GITHUB_OUTPUT
            echo "digest_no_sha=${digest#"sha256:"}" >> $GITHUB_OUTPUT
          done
      - name: Install Cosign
        uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # https://github.com/sigstore/cosign-installer/releases/tag/v3.10.1
        with:
          cosign-release: "v2.6.2"
      - name: Create SBOM of container image
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # https://github.com/anchore/sbom-action/releases/tag/v0.24.0
        with:
          image: ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
          artifact-name: logprep@${{ steps.build-and-push.outputs.digest_no_sha }}.spdx.json
          output-file: logprep@${{ steps.build-and-push.outputs.digest_no_sha }}.spdx.json
      - name: Sign image with a key and add sbom attestation
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
          cosign attest --yes --key env://COSIGN_PRIVATE_KEY --predicate logprep@${{ steps.build-and-push.outputs.digest_no_sha }}.spdx.json ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Scan image using Trivy
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # https://github.com/aquasecurity/trivy-action/releases/tag/v0.35.0
        env:
          TRIVY_PLATFORM: linux/amd64
          # use daily updated databases from main branch
          # https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
        with:
          scan-type: image
          image-ref: ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
          trivy-config: trivy.yaml
      - name: Build wheels
        run: |
          mkdir -p dist
          nix build .#dist.python311 -o dist_sl
          cp -rL dist_sl/* dist
          ls dist
