name: Reusable Container Build
on:
  workflow_call:
    inputs:
      tags:
        description: "Tags to apply to the image"
        required: true
        type: string
jobs:
  containerbuild:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          fetch-depth: 0
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@c818628b924a4bd863903a56c0e526db47bba6f4 # https://github.com/MrSquaare/ssh-setup-action/releases/tag/v3.1.3
        with:
          host: ${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
          private-key: ${{ secrets.BUILD_SERVER_ARM64_PRIVATE_KEY }}
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@c818628b924a4bd863903a56c0e526db47bba6f4 # https://github.com/MrSquaare/ssh-setup-action/releases/tag/v3.1.3
        with:
          host: ${{ secrets.BUILD_SERVER_ARM64_HOST_02 }}
          private-key: ${{ secrets.BUILD_SERVER_ARM64_PRIVATE_KEY }}
      - name: Set up Docker
        uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # https://github.com/docker/setup-docker-action/releases/tag/v4.7.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # https://github.com/docker/login-action/releases/tag/v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # https://github.com/docker/setup-buildx-action/releases/tag/v3.12.0
      #   with:
      #     driver: docker-container
      #     platforms: linux/amd64
      #     append: |
      #       - endpoint: ssh://root@${{ secrets.BUILD_SERVER_ARM64_HOST_01 }}
      #         platforms: linux/arm64
      #       - endpoint: ssh://root@${{ secrets.BUILD_SERVER_ARM64_HOST_02 }}
      #         platforms: linux/arm64
      - name: Generate Image Tags
        id: image-tag
        run: |
          python - <<EOF
          import os
          image = "ghcr.io/fkie-cad/logprep"
          version = "${{ matrix.python-version }}"
          tags = "${{ inputs.tags }}".split(",")
          full_image = [f"{image}:py{version}-{tag.strip()}" for tag in tags]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as file:
              file.write(f"tags={', '.join(full_image)}")
          EOF
      - run: |
          echo "${GITHUB_HEAD_REF}"

          export PY_VERSION=${{ matrix.python-version }}
          uv version "$(uv version --short).dev0+${GITHUB_REF##*/}.$(git rev-parse --short HEAD)"
          nix build .#docker.python${PY_VERSION//.} -o image
          docker load < image

          docker images
      # - name: Build image and push to registry
      #   uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # https://github.com/docker/build-push-action/releases/tag/v6.19.2
      #   id: build-and-push
      #   with:
      #     context: .
      #     push: true
      #     build-args: |
      #       PYTHON_VERSION=${{ matrix.python-version }}
      #       LOGPREP_VERSION=${{ env.LOGPREP_VERSION }}
      #     tags: ${{ steps.image-tag.outputs.tags }}
      #     platforms: "linux/arm64,linux/amd64"
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      - name: Extract image ID from sha256
        id: pushed-imageid
        run: |
          python - <<EOF
          import os
          imageid = "${{ steps.build-and-push.outputs.ImageID }}"
          digest = "${{ steps.build-and-push.outputs.Digest }}"
          with open(os.environ['GITHUB_OUTPUT'], 'a') as file:
              file.write(f"digest={digest.split(':')[1]}")
              file.write(f"imageid={imageid.split(':')[1]}")
          EOF
    # - name: Install Cosign
    #   uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # https://github.com/sigstore/cosign-installer/releases/tag/v3.10.1
    #   with:
    #     cosign-release: "v2.6.2"
    # - name: Create SBOM of container image
    #   uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # https://github.com/anchore/sbom-action/releases/tag/v0.24.0
    #   with:
    #     image: ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.Digest }}
    #     artifact-name: logprep@${{ steps.pushed-imageid.outputs.digest }}.spdx.json
    #     output-file: logprep@${{ steps.pushed-imageid.outputs.digest }}.spdx.json
    # - name: Sign image with a key and add sbom attestation
    #   run: |
    #     cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
    #     cosign attest --yes --key env://COSIGN_PRIVATE_KEY --predicate logprep@${{ steps.pushed-imageid.outputs.digest }}.spdx.json ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
    #   env:
    #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
    #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    # - name: Scan image using Trivy
    #   uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # https://github.com/aquasecurity/trivy-action/releases/tag/v0.35.0
    #   env:
    #     TRIVY_PLATFORM: linux/amd64
    #     # use daily updated databases from main branch
    #     # https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch
    #     TRIVY_SKIP_DB_UPDATE: true
    #     TRIVY_SKIP_JAVA_DB_UPDATE: true
    #   with:
    #     scan-type: image
    #     image-ref: ghcr.io/fkie-cad/logprep@${{ steps.build-and-push.outputs.digest }}
    #     trivy-config: trivy.yaml
