name: Publish Development Build

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-github-prerelease:
    runs-on: ubuntu-latest
    name: create and publish
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4

      - name: Initialize Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse --archs x86_64

      - name: Build binary wheel and a source tarball
        run: pipx run build --sdist

      - name: copy artifacts to dist folder
        run: cp ./wheelhouse/* ./dist/

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            dist/*
            LICENSE

  containerbuild:
    uses: ./.github/workflows/container-build.yml
    needs: create-github-prerelease
    secrets: inherit
    with:
      build-version: latest
      tags: "main, latest"
