name: Publish Development Build
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  create-github-prerelease:
    runs-on: ubuntu-24.04
    name: create and publish
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Set up Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # https://github.com/cachix/install-nix-action/releases/tag/v31.10.4
      - name: Build package
        run: |
          mkdir -p dist
          nix build .#dist.python311 -o dist_sl
          # hard copy contents to avoid issues with symlinks (which Nix creates by default)
          cp -rL dist_sl/* dist
      - name: Upload Artifact for next job
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # https://github.com/actions/upload-artifact/releases/tag/v7.0.0
        with:
          name: logprep-build
          path: dist
      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # https://github.com/marvinpinto/action-automatic-releases/releases/tag/v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            dist/*
            LICENSE
  containerbuild:
    uses: ./.github/workflows/container-build.yml
    needs: create-github-prerelease
    secrets: inherit
    with:
      tags: "main, latest"
