name: Publish Development Build
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  create-github-prerelease:
    runs-on: ubuntu-24.04
    name: create and publish
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Initialize Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # https://github.com/actions/setup-python/releases/tag/v6.2.0
        with:
          python-version: "3.11"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # https://github.com/docker/setup-qemu-action/releases/tag/v4.0.0
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse --archs x86_64
      - name: Build binary wheel and a source tarball
        run: pipx run build --sdist
      - name: copy artifacts to dist folder
        run: cp ./wheelhouse/* ./dist/
      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # https://github.com/marvinpinto/action-automatic-releases/releases/tag/v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            dist/*
            LICENSE
  containerbuild:
    uses: ./.github/workflows/container-build.yml
    needs: create-github-prerelease
    secrets: inherit
    with:
      tags: "main, latest"
