name: Push mirror
on:
  push:
    branches: ['**']
jobs:
  push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          fetch-depth: 0
      - name: mirror-repository
        uses: ppcad/mirror-action@1e6d5f53a19e3bf7bb85bdc9338b0890887dd8a0 # https://github.com/ppcad/mirror-action/releases/tag/v0.4.5
        with:
          REMOTE: ${{ secrets.GIT_REMOTE_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          GIT_PUSH_ARGS: '--force --quiet --no-progress'
          DEBUG: "false"
