name: Testing
on:
  workflow_call:
jobs:
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Perform tests for rust modules
        run: cargo test
  python:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        test-type: ["unit", "acceptance"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # https://github.com/astral-sh/setup-uv/releases/tag/v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # https://github.com/Azure/setup-helm/releases/tag/v5.0.0
        with:
          version: "latest"
        id: install
      - name: Install dependencies
        run: uv sync --frozen --extra dev
      - name: Perform ${{ matrix.test-type }} test
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: uv run pytest -vv tests/${{ matrix.test-type }}
